# Site settings
title: martingale
email: ""
description: > # this means to ignore newlines until "baseurl:"
  fair game where knowledge of past events never helps predict the mean of the future winnings
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: odavidlin_
github_username:  davidwclin

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      comments: true


# Build settings
markdown: kramdown
